import React, { createContext, useContext, useState } from 'react';
import { enUS, es } from 'date-fns/locale';

const translations = {
    en: {
        sidebar: {
            subtitle: 'Manage your life.',
            tasks: 'Tasks',
            finance: 'Finance',
            inbox: 'INBOX',
            addTaskPlaceholder: '+ Add a task',
            journal: 'Journal'
        },
        home: {
            heroTitle: 'Your Second Brain',
            heroSubtitle: 'Powered by AI',
            heroDescription: 'Manage your personal life with an intelligent assistant that understands your tasks, finances and wellbeing.',
            startNow: 'Start Now',
            tryAI: 'Try AI',
            aiTools: 'AI Tools',
            modules: 'Modules',
            possibilities: 'Possibilities',
            featuresTitle: 'Everything you need',
            featuresSubtitle: 'A complete suite of tools to manage your personal life, connected and powered by artificial intelligence.',
            taskManagement: 'Task Management',
            taskManagementDesc: 'Organize your tasks in Inbox, To-Do and Done. Drag and drop to reorganize.',
            personalFinance: 'Personal Finance',
            personalFinanceDesc: 'Track income and expenses. Monthly budgets with alerts and savings goals.',
            personalJournal: 'Personal Journal',
            personalJournalDesc: 'Write entries with rich editor. Track your mood and energy.',
            crossLinkProjects: 'Cross-Link Projects',
            crossLinkProjectsDesc: 'Connect tasks, transactions and entries under unified projects.',
            aiAssistantTitle: 'Your Intelligent Personal Assistant',
            aiAssistantSubtitle: 'Talk to LifeOS AI in natural language. Ask for your daily summary, add expenses, create tasks or analyze your mood.',
            poweredBy: 'Powered by Groq',
            dailySummary: 'Auto daily summary',
            moodPatterns: 'Mood pattern analysis',
            budgetAlerts: 'Smart budget alerts',
            naturalCommands: 'Natural language commands',
            quickStartTitle: 'Start in Seconds',
            quickStartSubtitle: 'No learning curve. Just use the app.',
            step1Title: 'Choose a Module',
            step1Desc: 'Tasks, Finance, Journal or Projects from the sidebar.',
            step2Title: 'Add Content',
            step2Desc: 'Create tasks, log expenses or write in your journal.',
            step3Title: 'Ask the AI',
            step3Desc: 'Use chat for summaries, analysis or quick actions.',
            ctaTitle: 'Ready to organize your life?',
            ctaSubtitle: 'Start now and discover how a second brain can transform your productivity.',
            ctaButton: 'Start Free',
            footer: 'Your personal second brain • Powered by AI',
            toolsGuideTitle: 'What can I ask the AI?',
            toolsGuideSubtitle: 'Here are all the things you can ask LifeOS AI. Just write naturally!',
            taskTools: 'Tasks',
            financeTools: 'Finance',
            moodTools: 'Mood & Journal',
            projectTools: 'Projects',
            examplePrompts: 'Example prompts'
        },
        journal: {
            title: 'Journal',
            newEntry: 'New Entry',
            save: 'Save',
            cancel: 'Cancel',
            noEntries: 'No entries found.',
            placeholder: 'Write your thoughts...',
            back: 'Back',
            categories: 'Categories',
            allCategories: 'All Categories',
            addCategory: 'New Category',
            publicationDate: 'Publication Date',
            selectCategory: 'Select Category'
        },
        finance: {
            title: 'Finance',
            totalBalance: 'Total Balance',
            income: 'Income',
            expenses: 'Expenses',
            overview: 'OVERVIEW',
            addPlaceholder: 'Transaction...',
            addBtn: 'Add',
            exp: 'Exp',
            inc: 'Inc',
            currency: '$',
            allTime: 'All Time',
            monthly: 'Monthly',
            total: 'Total'
        },
        modal: {
            title: 'Edit Task',
            labelTitle: 'TITLE',
            labelDesc: 'DESCRIPTION',
            labelTime: 'TIME',
            labelStatus: 'STATUS',
            statusInbox: 'Inbox',
            statusTodo: 'To Do',
            statusDone: 'Done',
            delete: 'Delete',
            cancel: 'Cancel',
            save: 'Save',
            confirmDelete: 'Are you sure you want to delete this task?'
        },
        settings: {
            title: 'Settings',
            subtitle: 'Configure your AI assistant',
            securityNote: '🔒 Your API keys are stored securely in your browser. They are never sent to our servers.',
            aiConfigTitle: 'AI Configuration',
            aiConfigExplanation: 'This app uses <strong>OpenRouter</strong> to access 400+ AI models from all major providers',
            aiConfigDescription: 'OpenRouter gives you access to Claude, GPT, Gemini, Llama, and hundreds more models through a single API key',
            quickSetup: 'Quick Setup',
            step1Title: 'Get API Key',
            step1Desc: 'Visit openrouter.ai/keys',
            step2Title: 'Enter Below',
            step2Desc: 'Paste your sk-or-... key',
            step3Title: 'Choose Model',
            step3Desc: 'Select your preferred AI',
            apiKeyLabel: 'API Key',
            getApiKey: 'Get your API key',
            selectModel: 'Select Model',
            refreshModels: 'Refresh',
            loadingModels: 'Loading...',
            searchModels: 'Search models...',
            showAllModels: 'Show all models',
            showingAllModels: 'Showing all models',
            usingCachedModels: 'Using cached models (API unavailable)',
            saveSettings: 'Save Settings',
            saved: 'Saved!',
            directProviderAccess: 'Direct Provider Access',
            directProviderDesc: 'Configure individual providers (may have outdated models)',
            outdatedWarning: '<strong>Note:</strong> These providers may show outdated model lists. For the latest models, use OpenRouter above.',
            configured: 'Configured',
            needsApiKey: 'Needs API key',
            backupTitle: 'Data Backup & Restore',
            exportData: 'Export Data',
            exportDesc: 'Download JSON backup',
            importData: 'Import Data',
            importDesc: 'Drag & drop or click'
        }
    },
    es: {
        sidebar: {
            subtitle: 'Gestiona tu vida.',
            tasks: 'Tareas',
            finance: 'Finanzas',
            inbox: 'BANDEJA DE ENTRADA',
            addTaskPlaceholder: '+ Añadir tarea',
            journal: 'Diario'
        },
        home: {
            heroTitle: 'Tu Segundo Cerebro',
            heroSubtitle: 'Potenciado por IA',
            heroDescription: 'Gestiona tu vida personal con un asistente inteligente que entiende tus tareas, finanzas y bienestar.',
            startNow: 'Empezar Ahora',
            tryAI: 'Probar IA',
            aiTools: 'Herramientas IA',
            modules: 'Módulos',
            possibilities: 'Posibilidades',
            featuresTitle: 'Todo lo que necesitas',
            featuresSubtitle: 'Una suite completa de herramientas para gestionar tu vida personal, conectadas e impulsadas por inteligencia artificial.',
            taskManagement: 'Gestión de Tareas',
            taskManagementDesc: 'Organiza tus tareas en Inbox, To-Do y Done. Arrastra y suelta para reorganizar.',
            personalFinance: 'Finanzas Personales',
            personalFinanceDesc: 'Controla ingresos y gastos. Presupuestos mensuales con alertas y metas de ahorro.',
            personalJournal: 'Diario Personal',
            personalJournalDesc: 'Escribe entradas con editor rico. Rastrea tu estado de ánimo y energía.',
            crossLinkProjects: 'Proyectos Cross-Link',
            crossLinkProjectsDesc: 'Conecta tareas, transacciones y entradas bajo proyectos unificados.',
            aiAssistantTitle: 'Tu Asistente Personal Inteligente',
            aiAssistantSubtitle: 'Habla con LifeOS AI en lenguaje natural. Pregunta por tu resumen del día, añade gastos, crea tareas o analiza tu estado de ánimo.',
            poweredBy: 'Potenciado por Groq',
            dailySummary: 'Resumen diario automático',
            moodPatterns: 'Análisis de patrones de ánimo',
            budgetAlerts: 'Alertas de presupuesto inteligentes',
            naturalCommands: 'Comandos en lenguaje natural',
            quickStartTitle: 'Empieza en Segundos',
            quickStartSubtitle: 'No hay curva de aprendizaje. Solo usa la app.',
            step1Title: 'Elige un Módulo',
            step1Desc: 'Tareas, Finanzas, Diario o Proyectos desde la barra lateral.',
            step2Title: 'Añade Contenido',
            step2Desc: 'Crea tareas, registra gastos o escribe en tu diario.',
            step3Title: 'Pregunta a la IA',
            step3Desc: 'Usa el chat para resúmenes, análisis o acciones rápidas.',
            ctaTitle: '¿Listo para organizar tu vida?',
            ctaSubtitle: 'Empieza ahora y descubre cómo un segundo cerebro puede transformar tu productividad.',
            ctaButton: 'Comenzar Gratis',
            footer: 'Tu segundo cerebro personal • Potenciado por IA',
            toolsGuideTitle: '¿Qué puedo preguntarle a la IA?',
            toolsGuideSubtitle: 'Aquí tienes todo lo que puedes pedirle a LifeOS AI. ¡Solo escribe naturalmente!',
            taskTools: 'Tareas',
            financeTools: 'Finanzas',
            moodTools: 'Ánimo y Diario',
            projectTools: 'Proyectos',
            examplePrompts: 'Ejemplos de uso'
        },
        journal: {
            title: 'Diario',
            newEntry: 'Nueva Entrada',
            save: 'Guardar',
            cancel: 'Cancelar',
            noEntries: 'No se encontraron entradas.',
            placeholder: 'Escribe tus pensamientos...',
            back: 'Volver',
            categories: 'Categorías',
            allCategories: 'Todas',
            addCategory: 'Nueva Categoría',
            publicationDate: 'Fecha de Publicación',
            selectCategory: 'Seleccionar Categoría'
        },
        finance: {
            title: 'Finanzas',
            totalBalance: 'Balance Total',
            income: 'Ingresos',
            expenses: 'Gastos',
            overview: 'RESUMEN',
            addPlaceholder: 'Transacción...',
            addBtn: 'Añadir',
            exp: 'Gasto',
            inc: 'Ingr',
            currency: '€',
            allTime: 'Todo',
            monthly: 'Mensual',
            total: 'Total'
        },
        modal: {
            title: 'Editar Tarea',
            labelTitle: 'TÍTULO',
            labelDesc: 'DESCRIPCIÓN',
            labelTime: 'HORA',
            labelStatus: 'ESTADO',
            statusInbox: 'Bandeja de Entrada',
            statusTodo: 'Por Hacer',
            statusDone: 'Hecho',
            delete: 'Eliminar',
            cancel: 'Cancelar',
            save: 'Guardar',
            confirmDelete: '¿Estás seguro de que quieres eliminar esta tarea?'
        },
        settings: {
            title: 'Configuración',
            subtitle: 'Configura tu asistente IA',
            securityNote: '🔒 Tus claves API se almacenan de forma segura en tu navegador. Nunca se envían a nuestros servidores.',
            aiConfigTitle: 'Configuración IA',
            aiConfigExplanation: 'Esta app usa <strong>OpenRouter</strong> para acceder a más de 400 modelos IA de todos los proveedores principales',
            aiConfigDescription: 'OpenRouter te da acceso a Claude, GPT, Gemini, Llama y cientos de modelos más con una sola clave API',
            quickSetup: 'Configuración Rápida',
            step1Title: 'Obtén la Clave API',
            step1Desc: 'Visita openrouter.ai/keys',
            step2Title: 'Introdúcela Abajo',
            step2Desc: 'Pega tu clave sk-or-...',
            step3Title: 'Elige Modelo',
            step3Desc: 'Selecciona tu IA preferida',
            apiKeyLabel: 'Clave API',
            getApiKey: 'Obtener tu clave API',
            selectModel: 'Seleccionar Modelo',
            refreshModels: 'Actualizar',
            loadingModels: 'Cargando...',
            searchModels: 'Buscar modelos...',
            showAllModels: 'Mostrar todos los modelos',
            showingAllModels: 'Mostrando todos los modelos',
            usingCachedModels: 'Usando modelos en caché (API no disponible)',
            saveSettings: 'Guardar Configuración',
            saved: '¡Guardado!',
            directProviderAccess: 'Acceso Directo a Proveedores',
            directProviderDesc: 'Configurar proveedores individuales (pueden tener modelos desactualizados)',
            outdatedWarning: '<strong>Nota:</strong> Estos proveedores pueden mostrar listas de modelos desactualizadas. Para los modelos más recientes, usa OpenRouter arriba.',
            configured: 'Configurado',
            needsApiKey: 'Necesita clave API',
            backupTitle: 'Respaldo y Restauración de Datos',
            exportData: 'Exportar Datos',
            exportDesc: 'Descargar respaldo JSON',
            importData: 'Importar Datos',
            importDesc: 'Arrastra y suelta o haz clic'
        }
    }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState('en'); // Default to English as requested, switchable to ES

    const t = (section, key) => {
        return translations[language][section]?.[key] || key;
    };

    const getLocale = () => {
        return language === 'es' ? es : enUS;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, getLocale }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
